import logging
import sqlparse
from typing import List, Dict, Any, Set

logger = logging.getLogger(__name__)

class SecurityGate:
    """
    A service to validate and sanitize LLM-generated SQL queries before execution.
    It provides multiple layers of defense against potentially harmful queries.
    """

    def __init__(self, allowed_schemas: Set[str] = None):
        """
        Initializes the SecurityGate.

        Args:
            allowed_schemas (Set[str], optional): A set of schema names that queries
                                                  are allowed to access. If None,
                                                  schema validation is skipped.
        """
        self.allowed_schemas = allowed_schemas or set()

        # Layer 1: Keyword Blacklisting (Most basic defense) 
        # DML/DDL commands that modify or delete data/structures.
        self.DANGEROUS_KEYWORDS = {
            'DELETE', 'UPDATE', 'INSERT', 'DROP', 'TRUNCATE', 'ALTER', 'CREATE',
            'GRANT', 'REVOKE', 'EXEC', 'EXECUTE', 'MERGE'
        }
        
        # Keywords often used in malicious attacks.
        self.SUSPICIOUS_KEYWORDS = {
            'UNION', 'SLEEP', 'BENCHMARK', '--', ';', '/*', 'xp_cmdshell'
        }

    def validate_query(self, sql_query: str, schema_context: List[Dict[str, Any]] = None) -> bool:
        """
        The main validation method. It runs the query through all security checks.

        Args:
            sql_query (str): The SQL query generated by the LLM.
            schema_context (List[Dict[str, Any]], optional): The schema information that was
                                                             provided to the LLM. Used for
                                                             more advanced validation.

        Returns:
            bool: True if the query is deemed safe, False otherwise.
        """
        logger.info(f"Validating SQL query: {sql_query[:100]}...")

        # Check 1: Simple Blacklist Check
        if not self._is_blacklist_safe(sql_query):
            return False

        # Check 2: Query Structure and Type Validation 
        try:
            parsed = sqlparse.parse(sql_query)
            if not parsed:
                logger.warning("Security check failed: Query could not be parsed.")
                return False
            
            # We only allow a single SQL statement. Prevents statement injection.
            if len(parsed) > 1:
                logger.warning(f"Security check failed: Multiple statements detected ({len(parsed)}).")
                return False
            
            statement = parsed[0]
            
            # We only allow SELECT statements.
            if statement.get_type() != 'SELECT':
                logger.warning(f"Security check failed: Query type is '{statement.get_type()}', not 'SELECT'.")
                return False

            #Check 3: Schema and Table Whitelisting 
            # This check ensures the query only accesses tables it was supposed to.
            if schema_context and not self._only_accesses_allowed_tables(statement, schema_context):
                return False

        except Exception as e:
            logger.error(f"An error occurred during query parsing: {e}", exc_info=True)
            return False

        logger.info("SQL query passed all security checks.")
        return True

    def _is_blacklist_safe(self, sql_query: str) -> bool:
        """Checks if the query contains any blacklisted keywords."""
        query_upper = sql_query.upper()
        
        for keyword in self.DANGEROUS_KEYWORDS.union(self.SUSPICIOUS_KEYWORDS):
            # Use word boundaries to avoid matching substrings (e.g., 'UPDATE' in 'MY_UPDATED_TABLE')
            if f' {keyword} ' in query_upper or query_upper.startswith(keyword + ' '):
                logger.warning(f"Security check failed: Blacklisted keyword '{keyword}' found.")
                return False
        return True

    def _only_accesses_allowed_tables(self, statement: sqlparse.sql.Statement, schema_context: List[Dict[str, Any]]) -> bool:
        """
        Parses the query to extract all table identifiers and checks them against
        the provided schema context.
        """
        allowed_table_names = {table['name'] for table in schema_context}
        
        queried_tables = self._extract_tables_from_statement(statement)
        
        for table in queried_tables:
            if table not in allowed_table_names:
                logger.warning(f"Security check failed: Query attempts to access table '{table}' which was not in the provided context.")
                return False
        
        logger.debug(f"Table access check passed. Queried tables: {queried_tables}")
        return True

    def _extract_tables_from_statement(self, statement: sqlparse.sql.Statement) -> Set[str]:
        """A helper to recursively find all table identifiers in a parsed query."""
        tables = set()
        
        from_seen = False
        for token in statement.tokens:
            if token.is_keyword and token.normalized == 'FROM':
                from_seen = True
            elif from_seen and isinstance(token, sqlparse.sql.Identifier):
                # This will catch the main table and aliased tables
                tables.add(token.get_real_name())
            elif isinstance(token, sqlparse.sql.IdentifierList):
                for identifier in token.get_identifiers():
                    tables.add(identifier.get_real_name())
            # Recursively check for subqueries
            elif token.is_group:
                tables.update(self._extract_tables_from_statement(token))
                
        return tables